config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :facebook_requests, only: :create

  resources :facebook_pages, only: :index do
    resources :facebook_page_tabs, only: [:index, :create, :destroy]
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]


  class << self

    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
        user.email = auth.info.email
        user.email = "omniauth-#{auth.provider}-#{auth.uid}@facebook.com" unless user.email
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected

  def facebook_graph(token = nil)
    token = session[:access_token] unless token
    Koala::Facebook::API.new token, Rails.application.secrets.facebook_api_secret
  end
end

app/controllers/facebook_page_tabs_controller.rb
class FacebookPageTabsController < ApplicationController

  def index
    @page = page_graph.get_object(params[:facebook_page_id])
    @tabs = page_graph.get_connections(params[:facebook_page_id], 'tabs')

    Rails.logger.debug @page
    Rails.logger.debug @tabs
  end

  def create
    options = {
      app_id: Rails.application.secrets.facebook_app_id,
      custom_name: 'Custom name'
    }
    graph = page_graph.put_connections(page_id, "tabs", options)
    flash[:notice] = "Page tab added"
    redirect_to facebook_page_facebook_page_tabs_path page_id, token: token
  end

  def destroy
    options = {
      tab: params[:id]
    }
    graph = page_graph.delete_connections(page_id, "tabs", options)
    flash[:notice] = "Page tab removed"

    redirect_to facebook_page_facebook_page_tabs_path page_id, token: token
  end

  private

  def page_graph
    @graph ||= facebook_graph(token)
  end

  def page_id
    params[:facebook_page_id]
  end

  def token
    params[:token]
  end
end

app/controllers/facebook_pages_controller.rb
class FacebookPagesController < ApplicationController

  def index
    @pages = facebook_graph.get_connections("me", "accounts")
    Rails.logger.info @pages
  end
end

app/controllers/facebook_requests_controller.rb
class FacebookRequestsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create
    @oauth = Koala::Facebook::OAuth.new(
      Rails.application.secrets.facebook_app_id,
      Rails.application.secrets.facebook_api_secret,
      "http://localhost:3000/")

    Rails.logger.debug @oauth.parse_signed_request(params[:signed_request])
    redirect_to "/"
  end


  def base64_url_decode str
    encoded_str = str.gsub('-','+').gsub('_','/')
    encoded_str += '=' while !(encoded_str.size % 4).zero?
    Base64.decode64(encoded_str)
  end

  def decode_data str
    encoded_sig, payload = str.split('.')
    data = ActiveSupport::JSON.decode base64_url_decode(payload)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      session[:access_token] = request.env["omniauth.auth"].credentials.token
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/facebook_page_tabs/index.erb
<%= link_to 'Back', facebook_pages_path %>

<h1> <%= @page['name'] %> - #<%= @page['id'] %></h1>

<h3>Tabs</h3>
<ul>
  <% @tabs.each do |tab| %>
    <li>
      <h4> <%= tab['name'] %></h4>
      <ul>
        <li> <%= link_to 'Open', tab['link'], target: '_blank' %> </li>
        <li> Is permanent? <strong><%= tab['is_permanent'] %></strong> </li>
        <li> Position: <strong><%= tab['position'] %></strong> </li>

        <% if tab['application'] %>
          <li> Application: <strong> <%= tab['application']['name'] %> - #<%= tab['application']['id'] %> </strong>

          <% if tab['application']['id'] == Rails.application.secrets.facebook_app_id %>
            <%= form_tag(facebook_page_facebook_page_tab_path(@page['id'], "app_#{tab['application']['id']}"), method: :delete) do |f| %>

              <%= hidden_field :token, '', value: params[:token], name: 'token' %>

              <%= submit_tag 'Remove page tab' %>
            <% end %>
          <% end %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<%= form_for(facebook_page_facebook_page_tabs_path(params[:facebook_page_id])) do |f| %>

  <%= f.hidden_field :token, value: params[:token], name: 'token' %>
  <%= f.submit 'Add page tab' %>
<% end %>

app/views/facebook_pages/index.erb
<ul>
  <% @pages.each do |page| %>
    <li><%= page['name'] %>
    <%= link_to 'View tabs', facebook_page_facebook_page_tabs_path(page['id'], token: page['access_token']) %>
    </li>
  <% end %>
</ul>

app/views/home/index.html.erb
Hello <%= current_user.email %>!

<div>
  <%= link_to 'Pages', facebook_pages_path %>

</div>

<div>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookPageTab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= yield %>

</body>
</html>